version: "3"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    networks:
      - network_docker
  front-dev:
    image: front-dev
    build:
      context: ../front
    container_name: front-dev
    ports:
      - "8080:8080"
    networks:
      - network_docker
    volumes:
      - ../:/workspace:cached
      - ../front:/front
    # restart: always
    depends_on:
      - back-dev
  back-dev:
    image: back-dev
    build:
      context: ../java
    container_name: back-dev
    ports:
      - "9090:9090"
    environment:
      DEV_CONTAINERS: "true"
    volumes:
      - ../java:/java
    networks:
      - network_docker
    # restart: always
    depends_on:
      - postgres

networks:
  network_docker:
    driver: bridge
