version: '3.1'

services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mentorme
      POSTGRES_USER: mentorme
      POSTGRES_DB: mentorme