@Library("tqi-lib") _
node{
        def projectjava    = new com.tqi.Scrum()
        
        def scmVars = checkout scm
        
        def prdBranch = "master"
        
        projectjava.cleanDir()
        
    
        projectjava.cloneRepository(
            channel: "jenkins",
            projectName: "project-java"
        )

        def shortCommit = sh(returnStdout: true, script: "git log -n 1 --pretty=format:'%h'").trim()
    
        projectjava.buildJava(
            dockerCredentialsId: "dockerRegistryCredentials",
            channel: "jenkins",
            projectName: "project-java",
            master: prdBranch,
            builderName: "jdkeasy17"

        )     
        projectjava.deployPrd(
            channel: "jenkins",
            projectName: "project-java",
            serviceName: "project-java"
        )  
        }
        