// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRX8Zbko8hkVfBaCIp3Qhpdsubud0KE9s',
    appId: '1:915000041637:web:05c246c3a4e550d98bed4c',
    messagingSenderId: '915000041637',
    projectId: 'mentorme-40da8',
    authDomain: 'mentorme-40da8.firebaseapp.com',
    storageBucket: 'mentorme-40da8.appspot.com',
    measurementId: 'G-RWG1T0LQDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ7zMZp8mKV-2xg84ng8AitHWX1WhnoGY',
    appId: '1:915000041637:android:541553932e3c93358bed4c',
    messagingSenderId: '915000041637',
    projectId: 'mentorme-40da8',
    storageBucket: 'mentorme-40da8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5D3JcBbs5Qt3UWzlXdyeGqKeXcLak1wU',
    appId: '1:915000041637:ios:c892a2385e289e348bed4c',
    messagingSenderId: '915000041637',
    projectId: 'mentorme-40da8',
    storageBucket: 'mentorme-40da8.appspot.com',
    iosClientId: '915000041637-tm2fjj4m4eir6bno8cr8pgdtbagbtdsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5D3JcBbs5Qt3UWzlXdyeGqKeXcLak1wU',
    appId: '1:915000041637:ios:c892a2385e289e348bed4c',
    messagingSenderId: '915000041637',
    projectId: 'mentorme-40da8',
    storageBucket: 'mentorme-40da8.appspot.com',
    iosClientId: '915000041637-tm2fjj4m4eir6bno8cr8pgdtbagbtdsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
